/**
 * Search synonym and alias expansion for feline encyclopedia queries.
 * Extend this map as content grows — supports breed aliases, disease names,
 * common misspellings, and colloquial terms.
 */

export const SEARCH_SYNONYMS: Record<string, string[]> = {
  kitty: ["kitten", "cat", "feline"],
  kitten: ["kitty", "young cat"],
  feline: ["cat", "felid"],
  felid: ["cat", "feline", "wild cat"],
  puking: ["vomiting", "throwing up"],
  vomiting: ["puking", "throwing up", "regurgitation"],
  urination: ["peeing", "urinating", "micturition"],
  peeing: ["urination", "urinating"],
  poop: ["stool", "feces", "defecation"],
  stool: ["poop", "feces"],
  hairball: ["trichobezoar", "fur ball"],
  trichobezoar: ["hairball"],
  persian: ["persian cat", "flat face cat"],
  siamese: ["siamese cat", "meezer"],
  maine: ["maine coon", "maine coon cat"],
  ragdoll: ["rag doll cat"],
  bengal: ["bengal cat", "leopard cat domestic"],
  sphynx: ["hairless cat", "naked cat"],
  diabetes: ["diabetes mellitus", "sugar diabetes", "dm"],
  "diabetes mellitus": ["diabetes", "dm"],
  ckd: ["chronic kidney disease", "kidney disease", "renal failure"],
  "chronic kidney disease": ["ckd", "kidney disease", "renal disease"],
  uti: ["urinary tract infection", "bladder infection"],
  fiv: ["feline immunodeficiency virus", "cat aids"],
  felv: ["feline leukemia virus", "leukemia"],
  hyperthyroid: ["hyperthyroidism", "overactive thyroid"],
  hypothyroid: ["hypothyroidism", "underactive thyroid"],
  chocolate: ["cocoa", "theobromine"],
  onion: ["onions", "allium"],
  garlic: ["allium"],
  lily: ["lilies", "lilium"],
  lilytoxic: ["lily", "lilies", "toxic lily"],
  tuna: ["canned tuna", "fish"],
  milk: ["dairy", "lactose"],
  lactose: ["milk", "dairy"],
  purr: ["purring", "purr sound"],
  meow: ["meowing", "vocalization"],
  hiss: ["hissing", "aggression sound"],
  knead: ["kneading", "making biscuits", "milk treading"],
  biscuits: ["kneading", "making biscuits"],
  zoomies: ["frenetic random activity periods", "frap", "crazy hour"],
  frap: ["zoomies", "frenetic random activity periods"],
  declaw: ["onychectomy", "declawing"],
  neuter: ["castration", "spay neuter", "sterilization"],
  spay: ["ovariohysterectomy", "neuter"],
  vet: ["veterinarian", "veterinary"],
  veterinarian: ["vet", "dvm"],
  dvm: ["veterinarian", "vet"],
  aspca: ["poison control", "animal poison control"],
  poison: ["toxic", "toxicity", "poisonous"],
  toxic: ["poisonous", "poison", "toxicity"],
  allergy: ["allergies", "allergic", "atopy"],
  asthma: ["feline asthma", "bronchial disease"],
  arthritis: ["joint pain", "degenerative joint disease", "djd"],
  cancer: ["neoplasia", "tumor", "malignancy"],
  tumor: ["cancer", "neoplasia", "mass"],
  flea: ["fleas", "ctenocephalides"],
  tick: ["ticks", "ixodes"],
  worm: ["parasite", "intestinal parasite", "helminth"],
  rabies: ["rabies virus", "lyssavirus"],
  calicivirus: ["calici", "feline calicivirus", "fcv"],
  panleukopenia: ["distemper", "feline distemper", "fpv"],
  distemper: ["panleukopenia", "feline panleukopenia"],
  ibd: ["inflammatory bowel disease", "chronic enteropathy"],
  pancreatitis: ["pancreas inflammation"],
  cardiomyopathy: ["heart disease", "hcm", "dcm"],
  hcm: ["hypertrophic cardiomyopathy", "heart disease"],
  dcm: ["dilated cardiomyopathy"],
  gingivitis: ["gum disease", "dental disease", "periodontal"],
  dental: ["teeth", "oral", "gingivitis", "periodontal"],
  obese: ["obesity", "overweight", "fat cat"],
  overweight: ["obese", "obesity", "weight"],
  skinny: ["underweight", "thin", "weight loss"],
  "weight loss": ["skinny", "underweight", "cachexia"],
  lethargy: ["tired", "weak", "low energy"],
  diarrhea: ["loose stool", "soft stool"],
  constipation: ["blocked", "straining"],
  sneeze: ["sneezing", "upper respiratory"],
  cough: ["coughing", "respiratory"],
  wheeze: ["wheezing", "asthma"],
  scratch: ["scratching", "itching", "pruritus"],
  itch: ["itching", "scratching", "pruritus"],
  bite: ["biting", "aggression"],
  aggression: ["aggressive", "hostile", "bite"],
  anxiety: ["stress", "fearful", "nervous"],
  stress: ["anxiety", "stressed"],
  litter: ["litter box", "toilet training"],
  "litter box": ["litter", "sandbox"],
  carrier: ["cat carrier", "travel crate"],
  brush: ["grooming brush", "slicker brush"],
  nail: ["claw", "nails", "claws"],
  claw: ["nail", "claws", "scratching post"],
  whisker: ["whiskers", "vibrissae"],
  tail: ["caudal", "tail language"],
  eye: ["ocular", "eyes", "vision"],
  ear: ["otic", "ears", "ear mites"],
  "ear mites": ["otodectes", "ear parasite"],
  mite: ["mites", "parasite"],
  mange: ["demodex", "notoedres", "skin mite"],
  ringworm: ["dermatophytosis", "fungal infection"],
  abscess: ["infection", "wound", "bite wound"],
  wound: ["injury", "abscess", "cut"],
  emergency: ["urgent", "emergency care", "er vet"],
  firstaid: ["first aid", "emergency care"],
  "first aid": ["firstaid", "emergency"],
  adopt: ["adoption", "rescue", "shelter"],
  rescue: ["adopt", "shelter", "rehome"],
  shelter: ["rescue", "adoption", "humane society"],
  senior: ["geriatric", "old cat", "elderly cat"],
  geriatric: ["senior", "old cat"],
  indoor: ["inside cat", "house cat"],
  outdoor: ["outside cat", "free roaming"],
  wild: ["wild cat", "felid", "big cat"],
  lion: ["panthera leo", "big cat"],
  tiger: ["panthera tigris", "big cat"],
  cheetah: ["acinonyx jubatus"],
  leopard: ["panthera pardus"],
  lynx: ["wild lynx", "bobcat"],
  bobcat: ["lynx rufus"],
  serval: ["leptailurus serval"],
  savannah: ["savannah cat", "serval hybrid"],
  calico: ["tortoiseshell", "tri color cat"],
  tortie: ["tortoiseshell", "calico"],
  tabby: ["striped cat", "mackerel tabby"],
  tuxedo: ["black and white cat", "bicolor"],
  orange: ["ginger cat", "marmalade cat"],
  ginger: ["orange cat", "marmalade"],
  black: ["black cat", "melanistic"],
  white: ["white cat", "deaf white cat"],
  blue: ["gray cat", "grey cat", "russian blue"],
  gray: ["grey", "blue cat"],
  grey: ["gray", "blue cat"],
  longhair: ["long hair", "long haired cat"],
  shorthair: ["short hair", "short haired cat"],
  hairless: ["sphynx", "naked cat"],
  hypoallergenic: ["allergy friendly", "low allergen"],
  hypo: ["hypoallergenic"],
  raw: ["raw diet", "barf", "raw feeding"],
  barf: ["raw diet", "biologically appropriate raw food"],
  kibble: ["dry food", "dry cat food"],
  wet: ["canned food", "wet food"],
  treat: ["treats", "snack"],
  water: ["hydration", "drinking"],
  hydration: ["water", "dehydration"],
  dehydrated: ["dehydration", "dry"],
  protein: ["amino acids", "meat"],
  taurine: ["amino acid", "essential nutrient"],
  vitamin: ["supplement", "nutrients"],
  supplement: ["vitamin", "nutraceutical"],
  probiotic: ["gut health", "microbiome"],
  enzyme: ["digestive enzyme"],
  insulin: ["diabetes treatment", "blood sugar"],
  antibiotic: ["antibiotics", "infection treatment"],
  steroid: ["corticosteroid", "prednisolone"],
  prednisolone: ["steroid", "prednisone"],
  metacam: ["meloxicam", "pain relief"],
  meloxicam: ["metacam", "nsaid"],
  gabapentin: ["pain", "anxiety medication"],
  cerenia: ["maropitant", "anti nausea"],
  convenia: ["cefovecin", "long acting antibiotic"],
  revolution: ["selamectin", "parasite prevention"],
  bravecto: ["fluralaner", "flea tick"],
  frontline: ["fipronil", "flea treatment"],
  advantage: ["imidacloprid", "flea treatment"],
  feliway: ["pheromone", "calming diffuser"],
  pheromone: ["feliway", "calming"],
  laser: ["laser pointer", "play"],
  catnip: ["nepeta", "nip"],
  nip: ["catnip"],
  silvervine: ["actinidia", "cat stimulant"],
  tree: ["cat tree", "climbing"],
  scratcher: ["scratching post", "scratch pad"],
  fountain: ["water fountain", "drinking fountain"],
  puzzle: ["food puzzle", "enrichment feeder"],
  enrichment: ["mental stimulation", "play"],
  train: ["training", "behavior modification"],
  clicker: ["clicker training", "positive reinforcement"],
  positive: ["positive reinforcement", "reward based"],
  punishment: ["aversive", "negative reinforcement"],
  socialization: ["socializing", "kitten socialization"],
  introduce: ["introduction", "new cat", "multi cat"],
  multi: ["multiple cats", "multi cat household"],
  territory: ["territorial", "marking"],
  mark: ["marking", "spraying", "urine marking"],
  spray: ["spraying", "urine marking", "marking"],
  hide: ["hiding", "withdrawn"],
  groom: ["grooming", "self grooming", "over grooming"],
  overgroom: ["over grooming", "psychogenic alopecia"],
  alopecia: ["hair loss", "bald patches"],
  "hair loss": ["alopecia", "balding"],
  bald: ["hair loss", "alopecia"],
  dandruff: ["flaky skin", "seborrhea"],
  fleaallergy: ["flea allergy dermatitis", "fad"],
  atopy: ["environmental allergy", "allergy"],
  foodallergy: ["food sensitivity", "adverse food reaction"],
  sensitivity: ["intolerance", "allergy"],
  intolerance: ["sensitivity", "food intolerance"],
  ibs: ["irritable bowel", "gi upset"],
  gi: ["gastrointestinal", "digestive", "stomach"],
  stomach: ["gastric", "gi", "abdomen"],
  liver: ["hepatic", "hepatitis"],
  kidney: ["renal", "nephron", "ckd"],
  renal: ["kidney", "nephrology"],
  bladder: ["urinary", "cystitis"],
  cystitis: ["bladder inflammation", "flutd", "fic"],
  flutd: ["feline lower urinary tract disease", "cystitis"],
  fic: ["feline idiopathic cystitis", "stress cystitis"],
  urethra: ["blocked cat", "urinary blockage"],
  blocked: ["urinary blockage", "obstruction"],
  crystal: ["urinary crystals", "struvite", "calcium oxalate"],
  struvite: ["magnesium ammonium phosphate", "crystals"],
  oxalate: ["calcium oxalate", "bladder stones"],
  stone: ["bladder stones", "urolith", "calculi"],
  urolith: ["bladder stone", "urinary stone"],
  thyroid: ["hyperthyroid", "hypothyroid"],
  adrenal: ["cushing", "addison"],
  pancreas: ["pancreatitis", "diabetes"],
  spleen: ["splenic"],
  lung: ["pulmonary", "respiratory"],
  heart: ["cardiac", "cardiomyopathy"],
  cardiac: ["heart", "cardiovascular"],
  blood: ["anemia", "hematology"],
  anemia: ["low red blood cells", "pale gums"],
  platelet: ["thrombocytopenia", "clotting"],
  clot: ["coagulation", "clotting disorder"],
  immune: ["immunology", "autoimmune"],
  autoimmune: ["immune mediated", "auto immune"],
  vaccine: ["vaccination", "immunization", "shot"],
  vaccination: ["vaccine", "immunization"],
  booster: ["vaccine booster", "annual shot"],
  rabiesvax: ["rabies vaccine", "rabies shot"],
  fvrcp: ["feline viral rhinotracheitis calicivirus panleukopenia"],
  felvax: ["leukemia vaccine"],
  microchip: ["chip", "identification"],
  chip: ["microchip", "pet id"],
  insurance: ["pet insurance", "health coverage"],
  cost: ["price", "expense", "how much"],
  price: ["cost", "expense"],
  lifespan: ["life expectancy", "longevity"],
  "life expectancy": ["lifespan", "longevity"],
  longevity: ["lifespan", "life expectancy"],
  age: ["life stage", "how old"],
  convert: ["calculator", "conversion"],
  calculator: ["calc", "tool"],
  checklist: ["check list", "to do list"],
  compare: ["comparison", "versus", "vs"],
  versus: ["compare", "vs"],
  vs: ["versus", "compare"],
};

const MISSPELLINGS: Record<string, string> = {
  persain: "persian",
  siammese: "siamese",
  siames: "siamese",
  maincoon: "maine coon",
  "main coon": "maine coon",
  ragdol: "ragdoll",
  bengel: "bengal",
  sphynix: "sphynx",
  sfynx: "sphynx",
  diabeties: "diabetes",
  diabetis: "diabetes",
  kideny: "kidney",
  kindey: "kidney",
  vomitting: "vomiting",
  diarhea: "diarrhea",
  diarreah: "diarrhea",
  diarrea: "diarrhea",
  constipated: "constipation",
  alergies: "allergies",
  alergy: "allergy",
  athsma: "asthma",
  athma: "asthma",
  arthitis: "arthritis",
  arthritus: "arthritis",
  hyperthyriod: "hyperthyroid",
  hyperthyroidism: "hyperthyroid",
  hypothyriod: "hypothyroid",
  tortishell: "tortoiseshell",
  tortiseshell: "tortoiseshell",
  tabbycat: "tabby",
  catip: "catnip",
  catnip: "catnip",
  feliwey: "feliway",
  frontlien: "frontline",
  advantag: "advantage",
  revolutione: "revolution",
  prednisone: "prednisolone",
  behavoir: "behavior",
  behviour: "behavior",
  nutrtion: "nutrition",
  nutrtition: "nutrition",
  anotomy: "anatomy",
  anatmy: "anatomy",
  symtom: "symptom",
  symtpom: "symptom",
  sympton: "symptom",
  diseas: "disease",
  disese: "disease",
  mediction: "medication",
  medicaton: "medication",
  veterinaran: "veterinarian",
  veterinarion: "veterinarian",
  emergancy: "emergency",
  emegency: "emergency",
  poision: "poison",
  posion: "poison",
  posionous: "poisonous",
  poisionous: "poisonous",
  lilly: "lily",
  lillies: "lilies",
  choclate: "chocolate",
  chocoate: "chocolate",
  onoin: "onion",
  onoins: "onions",
  garkic: "garlic",
  tuuna: "tuna",
  lacotse: "lactose",
  laktose: "lactose",
  kneeding: "kneading",
  puurring: "purring",
  meowing: "meow",
  zoomie: "zoomies",
  litterbox: "litter box",
  scratchpost: "scratching post",
  catree: "cat tree",
  hairbal: "hairball",
  furball: "hairball",
  flees: "fleas",
  flee: "flea",
  tics: "ticks",
  tic: "tick",
  wyrm: "worm",
  rabees: "rabies",
  ringworms: "ringworm",
  abcess: "abscess",
  abcesses: "abscess",
  firstaide: "first aid",
  adoptions: "adoption",
  geriatrik: "geriatric",
  seniour: "senior",
  outdor: "outdoor",
  inddor: "indoor",
  savanah: "savannah",
  servalcat: "serval",
  cheeta: "cheetah",
  lepard: "leopard",
  lyns: "lynx",
  panthera: "big cat",
  giner: "ginger",
  melanistic: "black cat",
  vibrissae: "whisker",
  otodectes: "ear mites",
  demodex: "mange",
  dermatophyte: "ringworm",
  trichobezoar: "hairball",
  panleuk: "panleukopenia",
  calici: "calicivirus",
  rhinotracheitis: "upper respiratory",
  herpesvirus: "fhv",
  fhv: "feline herpesvirus",
  fip: "feline infectious peritonitis",
  peritonitis: "fip",
  felv: "feline leukemia",
  fiv: "feline immunodeficiency virus",
  hcm: "hypertrophic cardiomyopathy",
  dcm: "dilated cardiomyopathy",
  ibd: "inflammatory bowel disease",
  giardia: "parasite",
  coccidia: "parasite",
  toxoplasma: "toxoplasmosis",
  toxoplasmosis: "toxoplasma",
  heartworm: "dirofilaria",
  dirofilaria: "heartworm",
  tapeworm: "dipylidium",
  roundworm: "toxocara",
  hookworm: "ancylostoma",
  whipworm: "trichuris",
  lungworm: "aelurostrongylus",
  giardiasis: "giardia",
  coccidiosis: "coccidia",
  pyometra: "uterine infection",
  mammary: "breast cancer",
  mastitis: "mammary infection",
  dystocia: "difficult birth",
  queening: "birth kittens",
  gestation: "pregnancy",
  pregancy: "pregnancy",
  pregnent: "pregnant",
  neutering: "neuter",
  spaying: "spay",
  castration: "neuter",
  ovariohysterectomy: "spay",
  onychectomy: "declaw",
  dentalclean: "dental cleaning",
  anasthesia: "anesthesia",
  anesthesa: "anesthesia",
  radiograph: "xray",
  xray: "radiograph",
  ultrasound: "sonogram",
  sonogram: "ultrasound",
  mri: "magnetic resonance imaging",
  ct: "computed tomography",
  biopsy: "tissue sample",
  cytology: "cell sample",
  histopath: "biopsy",
  bloodwork: "blood test",
  bloodtest: "blood work",
  cbc: "complete blood count",
  chem: "chemistry panel",
  urinalysis: "urine test",
  urinetest: "urinalysis",
  fecal: "stool test",
  sttest: "fecal test",
  titers: "antibody test",
  titer: "antibody test",
  pcr: "polymerase chain reaction",
  elisa: "snap test",
  snap: "elisa test",
  felvtest: "leukemia test",
  fivtest: "fiv test",
  felvcombo: "combo test",
};

export function expandSearchQuery(query: string): string[] {
  const normalized = query.toLowerCase().trim();
  const queries = new Set<string>();

  function expandSingle(term: string) {
    if (!term) return;
    queries.add(term);

    if (MISSPELLINGS[term]) {
      queries.add(MISSPELLINGS[term]);
    }

    for (const [synonymTerm, synonyms] of Object.entries(SEARCH_SYNONYMS)) {
      if (term.includes(synonymTerm) || synonymTerm.includes(term)) {
        queries.add(synonymTerm);
        synonyms.forEach((s) => queries.add(s));
      }
    }

    if (SEARCH_SYNONYMS[term]) {
      SEARCH_SYNONYMS[term].forEach((s) => queries.add(s));
    }
  }

  expandSingle(normalized);

  const tokens = normalized.split(/\s+/).filter((t) => t.length >= 2);
  for (const token of tokens) {
    expandSingle(token);
  }

  return [...queries];
}

export function getSynonymsForTerm(term: string): string[] {
  const normalized = term.toLowerCase();
  return SEARCH_SYNONYMS[normalized] ?? [];
}
